/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.example.biblio.models

import com.example.biblio.models.Genre

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param genreId 
 * @param title 
 * @param isbn 
 * @param description 
 * @param author 
 * @param publisher 
 * @param lang 
 * @param publishedDate 
 * @param format 
 * @param pageCount 
 * @param price 
 * @param coverUrl 
 * @param coverSm 
 * @param coverMd 
 * @param coverLg 
 * @param createdAt 
 * @param updatedAt 
 * @param genre 
 */


data class Book (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "genre_id")
    val genreId: kotlin.Int? = null,

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "isbn")
    val isbn: kotlin.String? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "author")
    val author: kotlin.String? = null,

    @Json(name = "publisher")
    val publisher: kotlin.String? = null,

    @Json(name = "lang")
    val lang: kotlin.String? = null,

    @Json(name = "published_date")
    val publishedDate: kotlin.String? = null,

    @Json(name = "format")
    val format: kotlin.String? = null,

    @Json(name = "page_count")
    val pageCount: kotlin.Int? = null,

    @Json(name = "price")
    val price: java.math.BigDecimal? = null,

    @Json(name = "cover_url")
    val coverUrl: kotlin.String? = null,

    @Json(name = "cover_sm")
    val coverSm: kotlin.String? = null,

    @Json(name = "cover_md")
    val coverMd: kotlin.String? = null,

    @Json(name = "cover_lg")
    val coverLg: kotlin.String? = null,

    @Json(name = "created_at")
    val createdAt: kotlin.String? = null,

    @Json(name = "updated_at")
    val updatedAt: kotlin.String? = null,

    @Json(name = "genre")
    val genre: Genre? = null

) {


}

