/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.example.biblio.data.remote.dto

import com.squareup.moshi.Json

/**
 * 
 *
 * @param currentPage 
 * @param `data` 
 * @param firstPageUrl 
 * @param from 
 * @param lastPage 
 * @param lastPageUrl 
 * @param nextPageUrl 
 * @param path 
 * @param perPage 
 * @param prevPageUrl 
 * @param to 
 * @param total 
 */


data class BookPaginatedResponse (

    @Json(name = "current_page")
    val currentPage: Int? = null,

    @Json(name = "data")
    val `data`: List<Book>? = null,

    @Json(name = "first_page_url")
    val firstPageUrl: String? = null,

    @Json(name = "from")
    val from: Int? = null,

    @Json(name = "last_page")
    val lastPage: Int? = null,

    @Json(name = "last_page_url")
    val lastPageUrl: String? = null,

    @Json(name = "next_page_url")
    val nextPageUrl: String? = null,

    @Json(name = "path")
    val path: String? = null,

    @Json(name = "per_page")
    val perPage: Int? = null,

    @Json(name = "prev_page_url")
    val prevPageUrl: String? = null,

    @Json(name = "to")
    val to: Int? = null,

    @Json(name = "total")
    val total: Int? = null

) {


}

