/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.example.biblio.data.remote.dto


import com.squareup.moshi.Json

/**
 * 
 *
 * @param snapToken 
 * @param orderId 
 */


data class PaymentSubscribeResponse (

    @Json(name = "snap_token")
    val snapToken: String? = null,

    @Json(name = "order_id")
    val orderId: String? = null

) {


}

