/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.example.biblio.data.remote.dto


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.time.OffsetDateTime

/**
 * 
 *
 * @param id 
 * @param name 
 * @param email 
 * @param emailVerifiedAt 
 * @param createdAt 
 * @param updatedAt 
 * @param role 
 * @param avatarUrl 
 * @param subscribedUntil 
 * @param avatar 
 * @param isSubscribed 
 */

@JsonClass(generateAdapter = true)
data class User (

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "email")
    val email: kotlin.String? = null,

    @Json(name = "email_verified_at")
    val emailVerifiedAt: java.time.OffsetDateTime? = null,

    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime? = null,

    @Json(name = "updated_at")
    val updatedAt: java.time.OffsetDateTime? = null,

    @Json(name = "avatar_url")
    val avatarUrl: kotlin.String? = null,

    @Json(name = "subscribed_until")
    val subscribedUntil: java.time.OffsetDateTime? = null,

    @Json(name = "avatar")
    val avatar: kotlin.String? = null,

    @Json(name = "is_subscribed")
    val isSubscribed: kotlin.Boolean? = null,

    @Json(name = "progress")
    val progress: kotlin.collections.List<Progress>? = null

) {


}

