/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.example.biblio.data.remote.dto


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.time.OffsetDateTime

/**
 * 
 *
 * @param id 
 * @param name 
 * @param email 
 * @param emailVerifiedAt 
 * @param createdAt 
 * @param updatedAt 
 * @param role 
 * @param avatarUrl 
 * @param subscribedUntil 
 * @param avatar 
 * @param isSubscribed 
 */


data class User (

    @Json(name = "id")
    val id: Int? = null,

    @Json(name = "name")
    val name: String? = null,

    @Json(name = "email")
    val email: String? = null,

    @Json(name = "email_verified_at")
    val emailVerifiedAt: OffsetDateTime? = null,

    @Json(name = "created_at")
    val createdAt: OffsetDateTime? = null,

    @Json(name = "updated_at")
    val updatedAt: OffsetDateTime? = null,

    @Json(name = "role")
    val role: Role? = null,

    @Json(name = "avatar_url")
    val avatarUrl: String? = null,

    @Json(name = "subscribed_until")
    val subscribedUntil: OffsetDateTime? = null,

    @Json(name = "avatar")
    val avatar: String? = null,

    @Json(name = "is_subscribed")
    val isSubscribed: Boolean? = null

) {

    /**
     * 
     *
     * Values: user,admin
     */
    @JsonClass(generateAdapter = false)
    enum class Role(val value: String) {
        @Json(name = "user") user("user"),
        @Json(name = "admin") admin("admin");
    }

}

